config/routes.rb
Rails.application.routes.draw do
  resources :events
  root 'welcome#index'
  get '/auth/:provider/callback', to: 'session#create'
  delete '/logout', to: 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :owner, class_name: "User"

  validates :name, length: { maximum: 50 }, presence: true
  validates :place, length: { maximum: 100 }, presence: true
  validates :content, length: { maximum: 2000 }, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
  validate :start_at_should_be_before_end_at

  def created_by?(user)
    return false unless user

    owner_id == user.id
  end

  private
  def start_at_should_be_before_end_at
    return unless start_at && end_at

    if start_at >= end_at
      errors.add(:start_at, "は終了時間よりも前に設定してください")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, class_name: 'Event', foreign_key: "owner_id"

  def self.find_or_create_from_auth_hash!(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    nickname = auth_hash[:info][:nickname]
    image_url = auth_hash[:info][:image]

    User.find_or_create_by!(provider: provider, uid: uid) do |user|
      user.name = nickname
      user.image_url = image_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate
  helper_method :logged_in?, :current_user

  private
  def logged_in?
    !!session[:user_id]
  end

  def current_user
    return unless session[:user_id]
    @current_user = User.find(session[:user_id])
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: 'ログインしてください'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate, only: :show

  def index
    @events = Event.where("start_at > ?", Time.zone.now).order(:start_at)
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)
  
    if @event.save
      redirect_to @event, notice: "作成しました"
    else
      render :new, status: :unprocessable_entity
    end
  end
  

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = current_user.created_events.find(params[:id])
  end

  def update
    @event = current_user.created_events.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: "更新しました"
    end
  end

  def destroy
    @event = current_user.created_events.find(params[:id])
    @event.destroy!
    redirect_to root_path, notice: "削除しました"
  end

  private
  def event_params
    params.require(:event).permit(
      :name, :place, :content, :start_at, :end_at
    )
  end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :authenticate, only: :create
  def create
    user = User.find_or_create_from_auth_hash!(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path,notice: "ログインしました"
  end

  def destroy
    reset_session
    redirect_to root_path, notice: "ログアウトしました"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_errors.html.haml
.alert.alter-danger
  %ul.mb-0
    - errors.full_messages.each do |message|
      %li= message

app/views/events/create.js.erb
document.getElementById("errors").innerHTML = "<%= j(render("errors", errors: @event.errors)) %>";

app/views/events/edit.html.haml
- now = Time.zone.now

%h1.mt-2 イベント情報編集

= form_with(model: @event, class: "form-horizontal") do |f|
  #errors
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :place
    = f.text_field :place, class: "form-control"
  .form-group
    = f.label :start_at
    %div
      = f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1, class: "form-control"
  .form-group
    = f.label :end_at
    %div
      = f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1, class: "form-control"
  .form-group
    = f.label :content
    = f.text_area :content, class: "form-control", rows: 10
  = f.submit class: "btn btn-primary"

app/views/events/new.html.haml
- now = Time.zone.now

%h1.mt-2 イベント作成

= form_with(model: @event, class: "form-horizontal") do |f|
  #errors
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :place
    = f.text_field :place, class: "form-control"
  .form-group
    = f.label :start_at
    %div
      = f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1, class: "form-control"
  .form-group
    = f.label :end_at
    %div
      = f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1, class: "form-control"
  .form-group
    = f.label :content
    = f.text_area :content, class: "form-control", rows: 10
  = f.submit class: "btn btn-primary"

app/views/events/show.html.haml
%h1.mt-3.mb-3= @event.name
.row
  .col-8
    .card.mb-2
      %h5.card-header イベント内容
      .card-body
        %p.card-text= @event.content
    .card.mb-2
      %h5.card-header 開催時間
      .card-body
        %p.card-text= "#{l(@event.start_at, format: :long)} - #{l(@event.end_at, format: :long)}"

    .card.mb-2
      %h5.card-header 開催箇所
      .card-body
        %p.card-text= @event.place
    .card.mb-2
      %h5.card-header 主催者
      .card-body
        = link_to("https://github/#{@event.owner.name}", class: "card-link") do
          = image_tag @event.owner.image_url, height: 50, width: 50
          = "@#{@event.owner.name}"
  .col-4
    - if @event.created_by?(current_user)
      = link_to "イベントを編集する", edit_event_path(@event), class: "btn-info btn-lg btn-block"
      = link_to "イベントを削除する", event_path(@event), class: "btn-info btn-lg btn-block", method: :delete, data: { confirm: "本当に削除しますか?" }

app/views/events/update.js.erb
document.getElementById("errors").innerHTML = "<%= j(render("errors", errors: @event.errors)) %>";

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AwesomeEvents
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header.navbar.navbar-expand-sm.navbar-light.bg-light
      .container
        = link_to "AwesomeEvents", root_path, class: "navbar-brand mr-auto"
        %ul.navbar-nav
          %li.nav-item
            = link_to "イベントを作る", new_event_path, class: "nav-link"
          - if logged_in?
            %li.nav-item
              = link_to "ログアウト", logout_path, class: "nav-link", method: :delete

          - else
            %li.nav-item
              = link_to "GitHubでログイン", "/auth/github", class: "nav-link", method: :post
      .container
        - if flash.notice 
          .alert.alert-success
            = flash.notice
        - if flash.notice
          .alert.alert-danger
            = flash.alert
        = yield

app/views/welcome/index.html.haml
%h1 イベント一覧

- if Event.present?
  %ul.list-group
    - Event.all.each do |event|
      = link_to(event, class: "list-group-item list-group-item-action") do
        %h5.list-group-item-heading= event.name
        %p.mb-1= "#{l(event.start_at, format: :long)} - #{l(event.end_at, format: :long)}"
- else
  %p イベントがありません